[package]
name = "grid-geom-util"
version = "0.1.0"
edition = "2021"
authors = ["Tuulikki Unelma <tuulikki.unelma@proton.me>"]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
num = "^0.4"

[dev-dependencies]
itertools = "^0.12"
